// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

function Spacer(Props) {
  var width = Props.width;
  var height = Props.height;
  var width$1 = Belt_Option.getWithDefault(width, 0);
  var height$1 = Belt_Option.getWithDefault(height, 0);
  return React.createElement(ReactNative.View, {
              style: {
                height: height$1,
                width: width$1
              }
            });
}

var make = Spacer;

export {
  make ,
  
}
/* react Not a pure module */
